apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  DB_NAME: users_db
  # The value below should be the service name of your MySQL deployment.
  # This is used in the JDBC URL.
  JDBC_URL: jdbc:mysql://mysql-service:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Base64 encode your passwords and paste them here.
  # Example: echo -n "my-root-password" | base64
  DB_PASSWORD: eW91ci1wYXNzd29yZA==